Repository shirai91/neon-shooter-js, pull requests merged in 2019-11, with the labels that each got.

#2 Update GameObject class
  src/core/GameEngine.ts
  src/core/GameObject.ts
  src/objects/Ship.ts
  src/scenes/TestCubeScene.ts
Labels: enhancement

#4 Add ContentManager and GameManager class
  src/assetList.ts
  src/core/CameraManager.ts
  src/core/ContentManager.ts
  src/core/GameEngine.ts
  src/core/GameManager.ts
  src/core/GameObject.ts
  src/core/InputManager.ts
  src/core/ScriptableScene.ts
  src/core/uuid.ts
  src/index.ts
  src/objects/Ship.ts
  src/scenes/SceneConfig.ts
  src/scenes/SceneFactory.ts
  src/scenes/TestCubeScene.ts
  tsconfig.json
Labels: enhancement

#5 Fix ship orientation when moving
  src/core/GameObject.ts
  src/core/InputManager.ts
  src/objects/Ship.ts
Labels: bug

#6 Ns init wanderer
  src/core/GameEngine.ts
  src/core/GameManager.ts
  src/core/utils.ts
  src/index.ts
  src/objects/Ship.ts
  src/objects/wanderer.ts
  src/scenes/TestCubeScene.ts
Labels: inprogress
